routes/web.php
<?php

Route::get('/info', function () { phpinfo(); });

Route::get('/', function () { return view('auth.login'); });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/teste', 'HomeController@teste2')->name('teste');
// ------------------------------------------------------------------------
Route::group(['middleware' => ['auth']], function(){
  Route::get('inicial', function () {
    if(Auth::user()->empresa_id == 1) return redirect()->route('empresa.index');
      if(Auth::user()->empresa_id > 1) return redirect()->route('pasta.index');
      });
  // ALERTAS
  Route::resource('alerta', 'AlertaController');
  // PERFIL
  Route::post('/perfil/SalvarImgS3/', 'PerfilController@SalvarImgS3')->name('fotoperfil');
  Route::resource('perfil', 'PerfilController');
  Route::post('/perfilemp/SalvarImgS3/', 'PerfilEmpController@SalvarImgS3')->name('fotoemp');
  Route::resource('perfilemp', 'PerfilEmpController');
  // PERFIS
  Route::get('/perfil_emp', 'HomeController@perfil_emp')->name('perfil_emp');
  Route::get('/perfil_usu', 'HomeController@perfil_usu')->name('perfil_usu');
  // USUARIOS
  Route::resource('usuario', 'UserController');
  Route::get('usuario/apaga/{id}','UserController@apaga')->name('apaga_usuario');
  Route::get('usuario/trocaSenha/{id}','UserController@trocaSenha')->name('trocaSenha_usuario');
  // GRUPOS
  Route::resource('grupo', 'GrupoController');
  Route::get('grupo/apaga/{id}','GrupoController@apaga')->name('apaga_grupo');
  // EMPRESAS
  Route::resource('empresa', 'EmpresaController');
  Route::get('empresa/apaga/{id}','EmpresaController@apaga')->name('apaga_empresa');
  // CLIENTES
  Route::resource('cliente', 'ClienteController');
  Route::get('cliente/apaga/{id}','ClienteController@apaga')->name('apaga_cliente');
  // ARQUIVOS
  Route::resource('arquivo', 'ArquivoController');
  Route::post('arquivo/SalvarArqS3/', 'ArquivoController@SalvarArqS3')->name('arquivos3');
  Route::post('arquivo/SalvarArquivos/', 'ArquivoController@SalvarArquivos')->name('arquivos');
  Route::get('arquivo/apaga/{id}','ArquivoController@apaga')->name('apaga_arquivo');
  Route::get('arquivo/baixar/{id}','ArquivoController@baixar')->name('baixar');
  Route::get('arquivo/salvaPdf/{id}/{end}','ArquivoController@salvaPdf')->name('salvaPdf');
  // PASTAS
  Route::resource('pasta', 'PastaController');
  Route::get('pasta/apaga/{id}','PastaController@apaga')->name('apaga_pasta');
  Route::get('pasta/abrir/{tipo}','PastaController@abrir')->name('abrir');
  // PERMISSAO
  Route::resource('permissao', 'PermissaoController');
  Route::post('permissao/mostrar','PermissaoController@mostrar')->name('mostrar_permissao');
  Route::get('permissao/compartilhar/{id}','PermissaoController@compartilhar')->name('compartilhar_permissao');
  Route::post('permissao/compStore/','PermissaoController@compStore')->name('compStore_permissao');
  Route::get('permissao/apagaPermissao/{id}','PermissaoController@apagaPermissao')->name('apagaPermissao');
  Route::put('permissao/moverpasta','PermissaoController@update');
  // SENDMAIL
  Route::get('mailsend/','MailController@SendEmail')->name('mailsend');
  Route::get('mailsend/cadastrado/{email}/{senha}/{empresa}','MailController@SendEmailCad')->name('user_cadastrado');
  Route::get('mailsend/trocaSenha/{email}/{senha}/{nome}','MailController@trocaSenha')->name('mailTrocaSenha');
  Route::get('mailsend/fluxo/{id}/{email}','MailController@fluxo')->name('mailFluxo');
  // TEMPLATE
  Route::resource('template', 'TemplateController');
  Route::get('template/apaga/{id}','TemplateController@apaga')->name('apaga_template');
  // DOCUMENTO fluxoAcao
  Route::resource('documento', 'DocumentoController');
  Route::get('documento/apaga/{id}','DocumentoController@apaga')->name('apaga_documento');
  Route::put('documento/rename/{id}','DocumentoController@rename')->name('renomear_documento');
  Route::get('documento/createDoc/{pasta}','DocumentoController@createDoc')->name('createDoc');
  Route::post('documento/createDocs','DocumentoController@createDocs')->name('createDocs');
  Route::get('documento/createTem/{pasta}','DocumentoController@createTem')->name('createTem');
  Route::post('documento/createDocTem/','DocumentoController@createDocTem')->name('createDocTem');
  Route::get('documento/pdf/{id}','DocumentoController@pdf')->name('pdf');
  Route::get('documento/enviaPdf/{id}/{emal}','DocumentoController@enviaPdf');
  Route::get('documento/reabreDoc/{id}','DocumentoController@reabreDoc')->name('reabreDoc');
  Route::post('documento/busca/','DocumentoController@busca')->name('buscar');
  Route::get('documento/show2/{id}/{end?}','DocumentoController@show2')->name('show2');
  Route::get('documento/fluxoAcao/{id}','DocumentoController@fluxoAcao')->name('fluxoAcao');
  Route::get('documento/download/{id}','DocumentoController@download');
  // FLUXO
  Route::resource('fluxo', 'FluxoController');
  Route::get('fluxo/apagaFluxo/{id}','FluxoController@apaga')->name('apagaFluxo');
  // CEP
  Route::post('consultaCEP','CepController@consultaCEP')->name('consultaCEP');
  // MOLDURA
  Route::resource('moldura', 'MolduraC');
  Route::get('moldura/apaga/{id}','MolduraC@apaga')->name('apaga_moldura');

  Route::get('session/get/{id}','SessionController@getSession');
  //Route::get('session/put/{id}/{id}','SessionController@putSession');
  Route::get('session/forget','SessionController@forgetSession');

  Route::get('/imprimir-documento/{id}', 'DocumentoController@Imprimir');
  Route::post('imprimir-moldura/', 'DocumentoController@ImprimirMoldura')->name('ImprimirMoldura');

  Route::get('/cabecalho', function() {
    return view('doc.cabecalho');
  })->name('cabecalho');

  Route::get('permissao_binario', function() {
    $binarios = DB::table('sog_permissoes_binario')->get();
    return $binarios;
  });

  Route::get('retorna_emails_cadastrados', 'UserController@RetornaEmails');
});

resources/views/doc/cabecalho.blade.php
@extends('layouts.soged')

@section('content')

<div class="container-fluid">

	<div class="card">
		<div class="mb-2 card-header">

			<div class="p-1">
				<i class="fa fa-file-alt"></i>
				<strong>Cadastrar Cabeçalho e Rodapé</strong>
			</div>

		</div>

		<div class="container">

			<form class="pb-5 form" action="#" method="post">

				<div class="form-group">
					<label for="exampleTextarea">Nome do modelo</label>
					<input type="text" class="form-control" name="moldura">
				</div>

				<div class="form-group">
					<label for="exampleTextarea">Cabeçalho</label>
					<textarea class="form-control"  id="ckeditor" name="cabecalho" rows="3"></textarea>
				</div>

				<div class="form-group">
					<label for="exampleTextarea">Rodapé</label>
					<textarea class="form-control"  id="ckeditor2" name="rodape" rows="3"></textarea>
				</div>

				<input type="hidden" name="background" value="" id="marca-dagua">

				<div class="demo-wrap upload-demo form-group">

					<label>Marca d'água</label>
					<div>
						<a class="btn file-btn btn-primary">
							<span>Upload</span>
							<input type="file" id="upload" value="Choose a file" accept="image/*" />
						</a>

						<button type="button" class="upload-result btn btn-secondary">Cortar</button>
						<button type="button" id="remover_marcadagua" class="btn btn-danger"><i class="fa fa-trash"></i></button>
					</div>

					<div class="upload-msg my-3">
						<i class="fa fa-image fa-2x"></i>
					</div>

					<div class="my-3">
						<img src="" width="248" height="350" class="uploaded-img">
					</div>

					<div class="upload-demo-wrap my-3">
						<div id="upload-demo"></div>
					</div>

					<small>Escolha imagens com tamanho mínimo de 2480 x 3508 para obter melhores resultados.</small>

				</div>

				<button class="btn btn-primary" type="button" id="submit">Salvar</button>

			</form>

		</div>

	</div>

</div>

<script>
	CKEDITOR.replace( 'ckeditor' );
	CKEDITOR.replace( 'ckeditor2' );

	var verificar_corte = 0;

	$(document).ready(function(){
		var $uploadCrop;

		function readFile(input) {
			if (input.files && input.files[0]) {
				var reader = new FileReader();

				reader.onload = function (e) {
					$('.upload-demo').addClass('ready');
					$uploadCrop.croppie('bind', {
						url: e.target.result
					}).then(function(){
					});

				}

				reader.readAsDataURL(input.files[0]);
			}
			else {
				swal("Desculpe, seu navegador não suporta esse recurso");
			}
		}

		$uploadCrop = $('#upload-demo').croppie({
			viewport: {
				width: 248,
				height: 350,
				type: 'square'
			},
			enableExif: true,
			boundary: {
				width: '100%',
				height: 450
			}
		});

		$('#upload').on('change', function () {
			readFile(this);
		});

		$('.upload-result').on('click', function (ev) {

			var size = { width: 2480, height: 3508 };

			$uploadCrop.croppie('result', {
				type: 'canvas',
				size: size
			}).then(function (resp) {
				$('#marca-dagua').val(resp);
				$('.uploaded-img').attr('src', resp);
				$('.uploaded-img').show();
				$('.upload-msg').hide();
				$('.upload-demo').removeClass('ready');
				verificar_corte++;
			});
		});

	});

	$('#submit').click(function(){

		if($('#upload').val() == "" || verificar_corte > 0){
			$('form').submit();
		}
		else{
			swal("Corte a imagem antes de salvar.");
		}

	});

	$('#remover_marcadagua').click(function(){

		$('.upload-demo').removeClass('ready');
		$('.uploaded-img').hide();
		$('.upload-msg').show();
		$('#marca-dagua').val('');
		$('#upload').val('');
		verificar_corte = 0;

	});


</script>

@endsection

resources/views/doc/editor.blade.php
@extends('layouts.soged')
@section('content')

<div class="container-fluid">

	@component('includes.alert')
	@endcomponent

	@if (isset($documento))
	<form class="" method="POST" action="{{route("documento.update",$documento->id_documento)}}">
		{{ method_field('PUT') }}
		<input type="hidden" name="id_documento" value="{{$documento->id_documento}}">
		<input type="hidden" name="template_id" value="{{$documento->template_id}}">
		@else
		<form class="" method="POST" action="{{route("documento.store")}}">
			<input type="hidden" name="pasta_id" value="{{$pasta}}">
			@endif
			@if (isset($tem))
			<input type="hidden" name="template_id" value="1">
			@endif
			{{ csrf_field() }}

			<!-- CABEÇALHO -->
			<div class="header p-3">
				
				<div class="d-flex align-items-center">
					@if (isset($tem))
					<i class="fa fa-file fa-2x text-white"></i>&nbsp;
					<input class="transparente ml-2" type="text" name="documento" value="{{ $documento->documento or 'Novo Template' }}" title="renomear" size="40">
					<input type="hidden" name="tem" value="{{ $documento->template_id or 1 }}">
					<a href="#" id="editar-nome-template"><i class="fa fa-edit text-white ml-3"></i></a>
					@else
					<i class="fa fa-file fa-lg text-white"></i>
					<div>
						<input class="transparente ml-2" type="text" name="documento" value="{{ $documento->documento or 'Novo Documento' }}" title="renomear" size="40">
						<a href="#" id="editar-nome-template"><i class="fa fa-edit text-white ml-3"></i></a>
					</div>
					@endif
				</div>
				

				@isset($templates)
				<div>
					<select class="form-control" name="template_id" required>
						<option value="">Selecione o tipo</option>
						@foreach ($templates as $key)
						<option value="{{$key->id_template}}">{{$key->template}}</option>
						@endforeach
					</select>
				</div>
				@endisset

				@if (isset($tem))
				<div class="text-right">
					<a class="text-white" href="#" data-toggle="modal" data-target="#tagsModal" title="Visualiza Tags existentes.">
						<i class="fa fa-question-circle fa-2x"></i>
					</a>
				</div>
				@endif

					{{-- @isset($documento->id_documento)
					<div class="text-right {{ isset($tipo)?"d-none":"" }}">
						<a class="text-white" href="{{route('fluxo.show',$documento->id_documento)}}" title="Fluxos do documento.">
							<i class="fa fa-exchange-alt mr-2"></i>
						</a>
					</div>
					@endisset --}}
				</div>
				<!-- CABEÇALHO -->

				<!-- TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO -->
				<textarea id="ckeditor" name="texto">
					{{ $texto->texto or old('texto') }}
					{{ $documento->texto or '' }}
					{{ $template->texto or ''  }}
				</textarea>
				<!-- TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO TEXTO -->
				<!-- BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS -->
				<div>
					<br>
				</div>
				<div class="row">

					<div class="col-lg-3 {{ isset($tipo) && $tipo == 3?"d-none":"" }}">
						@if (isset($documento))
						<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
							<button type="submit" class="btn btn-primary">Salvar</button>

							{{-- <div class="btn-group" role="group">
								<button id="btnGroupDrop1" type="button" class="btn {{ $documento->template_id > 0? "btn-success":"btn-primary"}} dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								</button>
								<div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
									<a class="btn btn-primary m-2" href="{{route('salvaPdf',[$documento->id_documento, $end])}}">
										<i class="fas fa-file-pdf"></i> Salva PDF
									</a>
									<a class="btn btn-primary m-2" href="{{url('/imprimir-documento/'.$documento->id_documento)}}">
										<i class="fa fa-print"></i> Imprimir
									</a>
									<a class="btn btn-primary m-2" href="#" data-toggle="modal" data-target="#molduraModal" data-id="{{ $documento->id_documento }}">
										<i class="fa fa-print"></i> Imprimir com moldura
									</a>
								</div>
							</div> --}}

						</div>

						@else
						<button class="form-control btn {{ isset($documento->template_id) > 0? "btn-success":"btn-primary"}}" type="submit">
							Criar {{isset($tem)?"Template":"Documento"}}
						</button>
						@endif
					</div>

					@isset($documento->fluxo)
					<div class="col-lg-6" style="display: {{ count($documento->fluxo) > 0?"":"none" }}">
						<div class="">
							<button class="form-control btn btn-success" type="submit" name="status" value="{{ $documento->status + 1 }}" onclick="return confirm('Confirma a finalização do documento?')">
								{{ isset($tipo) && $tipo == 3?"CONFIRMAR":"Finalizar" }} e enviar o Documento para o {{ $documento->status + 1 }}° passo</button>
							</div>
						</div>
						@endisset

					</div>
				</form>
				<!-- BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS BUTTONS -->

			</div>

			<script>
				CKEDITOR.replace( 'ckeditor',  {
					height: '700px'
				});



			</script>

			<!-- Modal MENU TAGS TEMPLATE -->
			<div class="modal fade bs-example-modal-lg" id="tagsModal" tabindex="-1" role="dialog" aria-labelledby="tagsModalLabel">
				<div class="modal-dialog modal-lg" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h4 class="modal-title" id="tagsModalLabel"><i class="fa fa-file"></i> TAGS </h4>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div  class="modal-body">
							<div class="">

								<table class="table table-condensed">
									<tr>
										<td>@nome_a</td> <td> → </td> <td>Nome da parte A</td>
										<td>@nome_b</td> <td> → </td> <td>Nome da parte B</td>
									</tr>
									<tr>
										<td>@cnpj_a</td> <td> → </td> <td>CNPJ da parte A</td>
										<td>@cnpj_b</td> <td> → </td> <td>CNPJ da parte B</td>
									</tr>
									<tr>
										<td>@razao_a</td> <td> → </td> <td>Razão da parte A</td>
										<td>@razao_b</td> <td> → </td> <td>Razão da parte B</td>
									</tr>
									<tr>
										<td>@ie_a</td> <td> → </td> <td>Inscrição Estadual da parte A</td>
										<td>@ie_b</td> <td> → </td> <td>Inscrição Estadual da parte B</td>
									</tr>
									<tr>
										<td>@uf_a</td> <td> → </td> <td>Estado da parte A</td>
										<td>@uf_b</td> <td> → </td> <td>Estado da parte B</td>
									</tr>
									<tr>
										<td>@cidade_a</td> <td> → </td> <td>Cidade da parte A</td>
										<td>@cidade_b</td> <td> → </td> <td>Cidade da parte B</td>
									</tr>
									<tr> <td>@bairro_a</td> <td> → </td> <td>Bairro da parte A</td>
										<td>@bairro_b</td> <td> → </td> <td>Bairro da parte B</td>
									</tr>
									<tr>
										<td>@rua_a</td> <td> → </td> <td>Logradouro da parte A</td>
										<td>@rua_b</td> <td> → </td> <td>Logradouro da parte B</td>
									</tr>
									<tr>
										<td>@numero_a</td> <td> → </td> <td>Número da parte A</td>
										<td>@numero_b</td> <td> → </td> <td>Número da parte B</td>
									</tr>
									<tr>
										<td>@cep_a</td> <td> → </td> <td>CEP da parte A</td>
										<td>@cep_b</td> <td> → </td> <td>CEP da parte B</td>
									</tr>
									<tr>
										<td>@comp_a</td> <td> → </td> <td>Complemento da parte A</td>
										<td>@comp_b</td> <td> → </td> <td>Complemento da parte B</td>
									</tr>

								</table>

							</div>
						</div>

					</div>
				</div>
			</div>
			<!-- Modal MENU TAGS TEMPLATE -->
			<!-- Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA -->
			<div class="modal fade" id="molduraModal" tabindex="-1" role="dialog" aria-labelledby="molduraModalLabel" aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="ModalLabel">
								<i class="fa fa-file-alt mr-2" aria-hidden="true"></i> Seleção de cabeçalhos e rodapés:
							</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							<form class="" action="{{ route("ImprimirMoldura") }}" method="post">
								{{ csrf_field() }}
								<input id="documento" type="hidden" name="id_documento" value="">

								<select class="form-control" name="id_moldura">
									<option value="0">Selecione...</option>
									@foreach ($molduras as $key)
									<option value="{{ $key->id_moldura }}">{{ $key->moldura }}</option>
									@endforeach
								</select>
							</div>
							<div class="modal-footer">
								<button type="submit" class="btn btn-primary"><i class="fa fa-print" aria-hidden="true"></i> Imprimir</button>
							</form>
						</div>
					</div>
				</div>
			</div>
			<!-- Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA Modal MOLDURA -->

			<script type="text/javascript">
				function troca(){ var txt = document.getElementById("ckeditor");  }


				$('#tagsModal').on('show.bs.modal', function (event) {
					var button = $(event.relatedTarget)
					var recipient = button.data('whatever')
					var modal = $(this)

					modal.find('.modal-footer input').val(recipient)
				})

				$('#molduraModal').on('show.bs.modal', function (event) {
					var button 	= $(event.relatedTarget)
					var var1 		= button.data('id')
					var modal 	= $(this)
					modal.find('#documento').val(var1)
				})
			</script>

			@if (session('success'))
			<script type="text/javascript">
				window.swal({
					type: 'success',
					title: 'Sucesso',
					text: '{{ session("success") }}',
				});
			</script>
			@endif

			@endsection

resources/views/doc/fluxo.blade.php
@extends('layouts.soged')

@section('content')

      <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
      <script>
      $( function() {
        $( "#sortable" ).sortable();
        $( "#sortable" ).disableSelection();
      } );
      </script>

    <div class="container-fluid">
      @component('includes.alert')
      @endcomponent

      <!-- BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB -->
          <ol class="breadcrumb bg-primary">
            <a class="text-white" href="#">
              <i class="fa fa-exchange-alt mr-2"></i>&nbsp; FLUXOS
            </a>
            <div class="col-md-1 text-right">
              <a class="text-white" href="{{route('documento.show',$idDoc)}}" title="Voltar">
                <i class="fa fa-arrow-circle-left fa-lg" aria-hidden="true"></i>
              </a>
            </div>
          </ol>
      <!-- BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB BREADCRUMB -->
      <!-- Blank div to give the page height to preview the fixed vs. static navbar-->
      <div class="row">

      <div class="col-md-7">
        <form class="form-control" action="{{route("fluxo.store")}}" method="post">
          {{ csrf_field() }}
          <input type="hidden" name="documento_id" value="{{$idDoc}}">
          <input type="hidden" name="statusDOC" value="">
          <input type="hidden" name="statusNEW" value="">

          <div class="row">
            <div class="col-md-7">
              <label for="fluxo">Nome do fluxo</label>
              <input id="fluxo" class="form-control form-control-sm" type="text" name="fluxo" value="">
            </div>
            <div class="col-md-5" id="div_sel_usu">
              <label for="sel_usu" id="id_select1">Usuários</label><br>
              <select id="sel_usu" class="custom-select" name="user_id[]" multiple>
                <option value="none">Selecione ...</option>
                @foreach ($usuarios as $key)
                  <option value="{{$key->id}}" title="{{$key->id.$key->name}}">{{$key->name}}</option>
                @endforeach
              </select>
            </div>

            <div class="col-md-6" id="div_sel_cli">
              <label for="sel_cli" id="id_select2">Clientes</label><br>
              <select id="sel_cli" class="custom-select" name="cliente_id[]" multiple>
                <option value="none">Selecione ...</option>
                @foreach ($clientes as $key)
                  <option value="{{$key->id}}">{{$key->cliente}}</option>
                @endforeach
              </select>
            </div>

          </div>

          <div class="row">
            <div class="col-md-12" id="div_mail">
              <label for="fluxo">Endereço de e-mail</label>
              <input id="myEmail" class="form-control form-control-sm" type="text" name="email" value="">
            </div>
          </div>

<div style="height: 20px;"></div>

          <div class="row">
            <div class="container">
            <div class="">
              <div class="btn-group btn-group-toggle">
              <label id="rd_enc" class="btn btn-dark">
                <input class="rbAtivoInativo" name="tipo" type="radio" value="1">&nbsp;
                <i class="far fa-hand-point-right" aria-hidden="true"></i> Encaminhar &nbsp;
              </label>
              <label id="rd_mail" class="btn btn-dark">
                <input class="rbAtivoInativo" name="tipo" type="radio" value="2">&nbsp;
                <i class="far fa-envelope" aria-hidden="true"></i> E-Mail &nbsp;
              </label>
              <label id="rd_conf" class="btn btn-dark">
                <input class="rbAtivoInativo" name="tipo" type="radio" value="3">&nbsp;
                <i class="far fa-thumbs-up" aria-hidden="true"></i> Confirmação &nbsp;
              </label>
            </div>
          </div>
        </div>
        </div>

        <div style="height: 20px;"></div>

        <div class="" id="div_btn">
          <input  class="btn btn-primary" type="submit" name="" value="Criar Fluxo">
        </div>
        </form>

        <script type="text/javascript">
        $('#div_sel_usu').hide('fast');
        $('#div_sel_cli').hide('fast');
        $('#div_mail').hide('fast');
        $('#div_btn').hide('fast');

        $(document).ready(function () {
          $('#rd_enc').click(function () {
            $('#div_sel_cli').hide('fast');
            $('#div_mail').hide('fast');
            $('#div_sel_usu').show('fast');
            $('#sel_cli').val('none');
          });
          $('#rd_mail').click(function () {
            $('#div_sel_usu').hide('fast');
            $('#div_mail').show('fast');
            $('#sel_usu').val('none');
          });
          $('#rd_conf').click(function () {
            $('#div_sel_cli').hide('fast');
            $('#div_mail').hide('fast');
            $('#div_sel_usu').show('fast');
            $('#sel_cli').val('none');
          });
          $('#myEmail').click(function () {
          $('#div_btn').show('fast');
          });

          $('#sel_usu').change(function() {
            if ($('#sel_usu').val() != 'none')
              $('#div_btn').show('fast');
             else
              $('#div_btn').hide('fast');
          });
        });
        </script>

      </div>
<!-- DIREITA -->
      <div class="col-md-4 form-control" style="display: {{count($fluxos) == 0?"none":""}}">
        <form class="" action="{{route("fluxo.update",1)}}" method="post">
          {{ csrf_field() }}{{ method_field('PUT') }}
          <input type="hidden" name="documento_id" value="{{$idDoc}}">

          <div style="cursor:move;">
            <div id="sortable">
              @foreach ($fluxos as $key)
                @php
                  if($key->tipo == 1) $icone = "far fa-hand-point-right";
                  elseif($key->tipo == 2) $icone = "far fa-envelope";
                  elseif($key->tipo == 3) $icone = "far fa-thumbs-up";
                @endphp
                <div class="input-group input-group-sm">
                  <span class="input-group-addon" id="sizing-addon3" title="Mover item">
                    ░&nbsp; {{$key->ordem - 1}}° &nbsp;
                    <i class="{{$icone}}" aria-hidden="true"></i>
                  </span>

                  <input type="text" name="" value="&nbsp;{{$key->fluxo}}" disabled>
                  <input type="hidden" class="form-control" name="teste[]" aria-describedby="sizing-addon3" value="{{$key->ordem}}">

                  <a class="btn btn-link btn-danger" href="{{route('apagaFluxo',$key->id_fluxo)}}" onclick="return confirm('Confirma a exclusão?')" title="Excluir item">
                    <i class="far fa-trash-alt text-danger" aria-hidden="true"></i>
                  </a>

                </div>
              @endforeach


            </div>
              <br>
            <input class="btn btn-primary" type="submit" name="" value="Gravar ordenação">

            </form>
          </div>
        </div>
      </div>

    </div>

  @endsection
  <!-- /.container-fluid-->

resources/views/doc/pdf.blade.php
@php
  echo $texto;
@endphp