routes/web.php
<?php

Route::get('/info', function () { phpinfo(); });

Route::get('/', function () { return view('auth.login'); });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/teste', 'HomeController@teste2')->name('teste');
// ------------------------------------------------------------------------
Route::group(['middleware' => ['auth']], function(){
  Route::get('inicial', function () {
    if(Auth::user()->empresa_id == 1) return redirect()->route('empresa.index');
      if(Auth::user()->empresa_id > 1) return redirect()->route('pasta.index');
      });
  // ALERTAS
  Route::resource('alerta', 'AlertaController');
  // PERFIL
  Route::post('/perfil/SalvarImgS3/', 'PerfilController@SalvarImgS3')->name('fotoperfil');
  Route::resource('perfil', 'PerfilController');
  Route::post('/perfilemp/SalvarImgS3/', 'PerfilEmpController@SalvarImgS3')->name('fotoemp');
  Route::resource('perfilemp', 'PerfilEmpController');
  // PERFIS
  Route::get('/perfil_emp', 'HomeController@perfil_emp')->name('perfil_emp');
  Route::get('/perfil_usu', 'HomeController@perfil_usu')->name('perfil_usu');
  // USUARIOS
  Route::resource('usuario', 'UserController');
  Route::get('usuario/apaga/{id}','UserController@apaga')->name('apaga_usuario');
  Route::get('usuario/trocaSenha/{id}','UserController@trocaSenha')->name('trocaSenha_usuario');
  // GRUPOS
  Route::resource('grupo', 'GrupoController');
  Route::get('grupo/apaga/{id}','GrupoController@apaga')->name('apaga_grupo');
  // EMPRESAS
  Route::resource('empresa', 'EmpresaController');
  Route::get('empresa/apaga/{id}','EmpresaController@apaga')->name('apaga_empresa');
  // CLIENTES
  Route::resource('cliente', 'ClienteController');
  Route::get('cliente/apaga/{id}','ClienteController@apaga')->name('apaga_cliente');
  // ARQUIVOS
  Route::resource('arquivo', 'ArquivoController');
  Route::post('arquivo/SalvarArqS3/', 'ArquivoController@SalvarArqS3')->name('arquivos3');
  Route::post('arquivo/SalvarArquivos/', 'ArquivoController@SalvarArquivos')->name('arquivos');
  Route::get('arquivo/apaga/{id}','ArquivoController@apaga')->name('apaga_arquivo');
  Route::get('arquivo/baixar/{id}','ArquivoController@baixar')->name('baixar');
  Route::get('arquivo/salvaPdf/{id}/{end}','ArquivoController@salvaPdf')->name('salvaPdf');
  // PASTAS
  Route::resource('pasta', 'PastaController');
  Route::get('pasta/apaga/{id}','PastaController@apaga')->name('apaga_pasta');
  Route::get('pasta/abrir/{tipo}','PastaController@abrir')->name('abrir');
  // PERMISSAO
  Route::resource('permissao', 'PermissaoController');
  Route::post('permissao/mostrar','PermissaoController@mostrar')->name('mostrar_permissao');
  Route::get('permissao/compartilhar/{id}','PermissaoController@compartilhar')->name('compartilhar_permissao');
  Route::post('permissao/compStore/','PermissaoController@compStore')->name('compStore_permissao');
  Route::get('permissao/apagaPermissao/{id}','PermissaoController@apagaPermissao')->name('apagaPermissao');
  Route::put('permissao/moverpasta','PermissaoController@update');
  // SENDMAIL
  Route::get('mailsend/','MailController@SendEmail')->name('mailsend');
  Route::get('mailsend/cadastrado/{email}/{senha}/{empresa}','MailController@SendEmailCad')->name('user_cadastrado');
  Route::get('mailsend/trocaSenha/{email}/{senha}/{nome}','MailController@trocaSenha')->name('mailTrocaSenha');
  Route::get('mailsend/fluxo/{id}/{email}','MailController@fluxo')->name('mailFluxo');
  // TEMPLATE
  Route::resource('template', 'TemplateController');
  Route::get('template/apaga/{id}','TemplateController@apaga')->name('apaga_template');
  // DOCUMENTO fluxoAcao
  Route::resource('documento', 'DocumentoController');
  Route::get('documento/apaga/{id}','DocumentoController@apaga')->name('apaga_documento');
  Route::put('documento/rename/{id}','DocumentoController@rename')->name('renomear_documento');
  Route::get('documento/createDoc/{pasta}','DocumentoController@createDoc')->name('createDoc');
  Route::post('documento/createDocs','DocumentoController@createDocs')->name('createDocs');
  Route::get('documento/createTem/{pasta}','DocumentoController@createTem')->name('createTem');
  Route::post('documento/createDocTem/','DocumentoController@createDocTem')->name('createDocTem');
  Route::get('documento/pdf/{id}','DocumentoController@pdf')->name('pdf');
  Route::get('documento/enviaPdf/{id}/{emal}','DocumentoController@enviaPdf');
  Route::get('documento/reabreDoc/{id}','DocumentoController@reabreDoc')->name('reabreDoc');
  Route::post('documento/busca/','DocumentoController@busca')->name('buscar');
  Route::get('documento/show2/{id}/{end?}','DocumentoController@show2')->name('show2');
  Route::get('documento/fluxoAcao/{id}','DocumentoController@fluxoAcao')->name('fluxoAcao');
  Route::get('documento/download/{id}','DocumentoController@download');
  // FLUXO
  Route::resource('fluxo', 'FluxoController');
  Route::get('fluxo/apagaFluxo/{id}','FluxoController@apaga')->name('apagaFluxo');
  // CEP
  Route::post('consultaCEP','CepController@consultaCEP')->name('consultaCEP');
  // MOLDURA
  Route::resource('moldura', 'MolduraC');
  Route::get('moldura/apaga/{id}','MolduraC@apaga')->name('apaga_moldura');

  Route::get('session/get/{id}','SessionController@getSession');
  //Route::get('session/put/{id}/{id}','SessionController@putSession');
  Route::get('session/forget','SessionController@forgetSession');

  Route::get('/imprimir-documento/{id}', 'DocumentoController@Imprimir');
  Route::post('imprimir-moldura/', 'DocumentoController@ImprimirMoldura')->name('ImprimirMoldura');

  Route::get('/cabecalho', function() {
    return view('doc.cabecalho');
  })->name('cabecalho');

  Route::get('permissao_binario', function() {
    $binarios = DB::table('sog_permissoes_binario')->get();
    return $binarios;
  });

  Route::get('retorna_emails_cadastrados', 'UserController@RetornaEmails');
});

resources/views/template/listMoldura.blade.php
@extends('layouts.soged')

@section('content')
<div class="container-fluid">
  <div class="card mb-3">

    <div class="card-header">

      <div>
        <i class="fa fa-file-alt"></i>
        <strong>Lista de molduras cabeçalhos e rodapés</strong>
      </div>

      <div>
        <div class="text-right">
          <a class="btn btn-primary" href="{{route('moldura.create')}}" title="Cadastrar Moldura">
            <i class="text-white fa fa-plus" aria-hidden="true"></i>
          </a>
        </div>
      </div>

    </div>

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">

          <thead>
            <tr>
              <th>Molduras</th>
              <th>Criação</th>
              <th class="text-center">Ações</th>
            </tr>
          </thead>

          <tbody>
            @foreach ($molduras as $key)
            <tr>
              <td>{{ $key->moldura }}</td>
              <td>{{ date( 'd/m/Y H:m' , strtotime($key->criado)) }}</td>
              <td class="actions">
                <a href="{{route('moldura.edit',$key->id_moldura)}}" title="Alterar moldura">
                  <i class="fa fa-edit" aria-hidden="true"></i>
                </a>
                <a href="{{route('apaga_moldura',$key->id_moldura)}}" title="Excluir moldura" class="excluir-registro">
                  <i class="text-danger fa fa-trash-alt" aria-hidden="true"></i>
                </a>
              </td>
            </tr>
            @endforeach
          </tbody>

        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Consultado por {{\Auth::user()->name}} em {{date('d/m/Y H:i')}}</div>
  </div>
</div>
@endsection

resources/views/template/listTemplate.blade.php
@extends('layouts.soged')

@section('content')
<div class="container-fluid">
  <div class="card mb-3">

    <div class="card-header">

      <div>
        <strong>Lista de Templates</strong>
      </div>
      
      <div>
        <div class="text-right">
          <a class="btn btn-primary" href="{{route('template.create')}}" title="Cadastrar Template">
            <i class="text-white fa fa-plus" aria-hidden="true"></i>
          </a>
        </div>
      </div>

    </div>

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Template</th>
              <th>Criação</th>
              <th class="text-center">Ações</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($templates as $key)
            <tr>
              <td>{{ $key->template }}</td>
              <td>{{ date( 'd/m/Y h:m' , strtotime($key->created_at)) }}</td>
              <td class="actions">
                <a href="{{route('template.edit',$key->id_template)}}" title="Alterar Template">
                  <i class="fa fa-edit" aria-hidden="true"></i>
                </a>
                <a href="{{route('apaga_template',$key->id_template)}}" title="Excluir Template" class="excluir-registro">
                  <i class="text-danger fa fa-trash-alt" aria-hidden="true"></i>
                </a>
              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Consultado por {{\Auth::user()->name}} em {{date('d/m/Y H:i')}}</div>
  </div>
</div>
@endsection

resources/views/template/moldura.blade.php
@extends('layouts.soged')

@section('content')

<div class="container-fluid">

	<div class="card">
		<div class="mb-2 card-header">

			<div class="p-1">
				<i class="fa fa-file-alt"></i>
				<strong>{{ isset($moldura)?"Editando ":"Cadastrar "}}Cabeçalho e Rodapé</strong>
			</div>

		</div>

		<div class="container">
			@if (isset($moldura))
				<form class="pb-5 form" action="{{route('moldura.update',$moldura->id_moldura)}}" method="post">
					{{ method_field('PUT') }}
			@else
				<form class="pb-5 form" action="{{route('moldura.store')}}" method="post">
			@endif
			{{ csrf_field() }}

				<div class="form-group">
					<label for="exampleTextarea">Nome da moldura</label>
					<input type="text" class="form-control" name="moldura" value="{{ $moldura->moldura or old('moldura') }}" required>
				</div>

				<div class="form-group">
					<label for="exampleTextarea">Cabeçalho</label>
					<textarea class="form-control" id="ckeditor" name="cabecalho" rows="3">{{ $moldura->cabecalho or old('cabecalho') }}</textarea>
				</div>

				<div class="form-group">
					<label for="exampleTextarea">Rodapé</label>
					<textarea class="form-control" id="ckeditor2" name="rodape" rows="3">{{ $moldura->rodape or old('rodape') }}</textarea>
				</div>

				<input type="hidden" name="fundo" value="" id="marca-dagua">

				<div class="row">

					@isset($moldura)
						<div class="col-lg-3">
							<label>Imagem atual</label>
							<img src="{{ env('APP_S3').$moldura->fundo }}" alt="" width="200">
						</div>
					@endisset

					<div class="">
						<div class="demo-wrap upload-demo form-group">

							<label>{{ isset($moldura)?"Trocar i":" I" }}magem de fundo</label>
							<div>
								<a class="btn file-btn btn-primary">
									<span>Enviar</span>
									<input type="file" id="upload" value="Choose a file" accept="image/*" />
								</a>

								<button type="button" class="upload-result btn btn-secondary">Cortar</button>
								<button type="button" id="remover_marcadagua" class="btn btn-danger"><i class="fa fa-trash"></i></button>
							</div>

							<div class="upload-msg my-3">
								<i class="fa fa-image fa-2x"></i>
							</div>

							<div class="my-3">
								<img src="" width="248" height="350" class="uploaded-img">
							</div>

							<div class="upload-demo-wrap my-3">
								<div id="upload-demo"></div>
							</div>

							<small>Escolha imagens com tamanho mínimo de 2480 x 3508 para obter melhores resultados.</small>

						</div>
					</div>
				</div>

				<button class="btn btn-primary loader-button" type="submit" id="submit">Salvar</button>
			</form>

		</div>

	</div>

</div>

<script>
	CKEDITOR.replace( 'ckeditor' );
	CKEDITOR.replace( 'ckeditor2' );

	var verificar_corte = 0;

	$(document).ready(function(){
		var $uploadCrop;

		function readFile(input) {
			if (input.files && input.files[0]) {
				var reader = new FileReader();

				reader.onload = function (e) {
					$('.upload-demo').addClass('ready');
					$uploadCrop.croppie('bind', {
						url: e.target.result
					}).then(function(){
					});

				}

				reader.readAsDataURL(input.files[0]);
			}
			else {
				swal("Desculpe, seu navegador não suporta esse recurso");
			}
		}

		$uploadCrop = $('#upload-demo').croppie({
			viewport: {
				width: 248,
				height: 350,
				type: 'square'
			},
			enableExif: true,
			boundary: {
				width: '100%',
				height: 450
			}
		});

		$('#upload').on('change', function () {
			readFile(this);
		});

		$('.upload-result').on('click', function (ev) {

			var size = { width: 2480, height: 3508 };

			$uploadCrop.croppie('result', {
				type: 'canvas',
				size: size
			}).then(function (resp) {
				$('#marca-dagua').val(resp);
				$('.uploaded-img').attr('src', resp);
				$('.uploaded-img').show();
				$('.upload-msg').hide();
				$('.upload-demo').removeClass('ready');
				verificar_corte++;
			});
		});

	});

	$('#submit').click(function(){

		if($('#upload').val() == "" || verificar_corte > 0){
			$('form').submit();
		}
		else{
			swal("Corte a imagem antes de salvar.");
		}

	});

	$('#remover_marcadagua').click(function(){

		$('.upload-demo').removeClass('ready');
		$('.uploaded-img').hide();
		$('.upload-msg').show();
		$('#marca-dagua').val('');
		$('#upload').val('');
		verificar_corte = 0;

	});


</script>

@endsection

resources/views/template/t.blade.php
@extends('layouts.soged')

@section('content')
  @php
    $texto = '@nome';
  @endphp

  <div class="content-wrapper">
    <div class="container-fluid">

      <div id="form">
      <div>
          <label for="txtFind" >Find:</label>
          <input id="txtFind" type="text" value="@nome" />
      </div>
      <div>
          <label for="txtReplace" >Replace:</label>
          <input id="txtReplace" type="text" value="=====" />
      </div>
      <div>
          <input id="btReplace" type="button" value="Substituir" />
      </div>
  <div>
    <textarea id="content" name="name" rows="8" cols="80">
      Lorem ipsum dolor sit amet, @nome consectetur adipiscing elit. {{ $texto }} Fusce molestie urna
    </textarea>

  <div id="content">
      Teste - Lorem Ipsum
      <p>Lorem ipsum dolor sit amet, @nome consectetur adipiscing elit. Fusce molestie urna dignissim justo iaculis aliquam. Ut auctor sit amet justo laoreet semper. Curabitur hendrerit ornare vulputate. In dictum dui et sem ultricies, id rhoncus nisi dignissim. Suspendisse ac enim sollicitudin, gravida leo eu, fringilla nisl. Suspendisse potenti. Aenean blandit ut purus eget varius. Fusce ornare pretium mauris, placerat viverra est facilisis in. Nunc elementum, leo ac tincidunt luctus, ipsum ipsum laoreet tortor, finibus pulvinar enim erat sit amet mi. Phasellus vulputate fringilla tortor, id tempus urna suscipit id. Vivamus ipsum libero, lacinia quis felis mollis, luctus viverra mi. Praesent id elementum metus, quis porttitor est. Integer condimentum rhoncus eros eget varius. Vestibulum vitae arcu libero.</p>
  </div>
  <button type="button" name="button" onclick="javascript:conversor()">teste</button>

    </div>
  </div>

<script type="text/javascript">
String.prototype.replaceAll = function(de, para){
  var str = this;
  var pos = str.indexOf(de);
  while (pos > -1){
  str = str.replace(de, para);
  pos = str.indexOf(de);
}
  return (str);
}

function conversor(){
  var result=document.getElementById('content').value;
  result.replaceAll('@nome','--------');
}
</script>

<script type="text/javascript">
var content = document.getElementById("content");
var txtFind = document.getElementById("txtFind");
var txtReplace = document.getElementById("txtReplace");
var btReplace = document.getElementById("btReplace");

var replaceText = function (elem, find, replace) {
    for (var indice in elem.childNodes) {
        var childNode = elem.childNodes[indice];
        if (childNode.nodeType == 3) {
            childNode.data = childNode.data.replace(find, replace);
        }

        if (childNode.nodeType == 1) {
            replaceText(childNode, find, replace);
        }
    }
}

btReplace.onclick = function () {
    var find = new RegExp(txtFind.value, 'g');
    var replace = txtReplace.value;

    replaceText(content, find, replace);
}

  function troca(){
    var txt = document.getElementById("ckeditor");
  }
</script>

@endsection

resources/views/template/template.blade.php
@extends('layouts.soged')

@section('content')

<div class="container-fluid">

  <div class="card">

    <div class="mb-2 card-header">

     <div class="p-1">
      <strong>{{ isset($template)?"Alterando Tipo de Template":"Cadastrar Tipo de Template"}}</strong>
    </div>

  </div>



  <div class="container">

    <div class="col-12 col-lg-6">

      @if (isset($template))
      <form class="pb-5 form" action="{{route('template.update',$template->id_template)}}" method="post">
        {{ method_field('PUT') }}
        @else
        <form class="pb-5 form" method="POST" action="{{ route('template.store') }}">
          <input type="hidden" name="empresa_id" value="{{\Auth::user()->empresa_id}}">
          @endif
          {{ csrf_field() }}

          <div class="row">

            <div class="form-group col-12">
              <label for="template">Tipo de template</label>
              <input name="template" type="text" class="form-control form-control-sm required" id="template" value="{{$template->template or old('template')}}" required autofocus>
              @if ($errors->has('template'))
              <span class="help-block">
                <strong>{{ $errors->first('template') }}</strong>
              </span>
              @endif
            </div>

          </div>

          @if (!isset($template))
          <button type="submit" class="btn btn-primary salvar-cadastro loader-button">Cadastrar</button>
          @else
          <button type="submit" class="btn btn-primary salvar-cadastro loader-button">Alterar</button>
          @endif  


        </div>

      </form>
    </div>
  </div>

  @endsection