routes/web.php
<?php

Route::get('/info', function () { phpinfo(); });

Route::get('/', function () { return view('auth.login'); });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/teste', 'HomeController@teste2')->name('teste');
// ------------------------------------------------------------------------
Route::group(['middleware' => ['auth']], function(){
  Route::get('inicial', function () {
    if(Auth::user()->empresa_id == 1) return redirect()->route('empresa.index');
      if(Auth::user()->empresa_id > 1) return redirect()->route('pasta.index');
      });
  // ALERTAS
  Route::resource('alerta', 'AlertaController');
  // PERFIL
  Route::post('/perfil/SalvarImgS3/', 'PerfilController@SalvarImgS3')->name('fotoperfil');
  Route::resource('perfil', 'PerfilController');
  Route::post('/perfilemp/SalvarImgS3/', 'PerfilEmpController@SalvarImgS3')->name('fotoemp');
  Route::resource('perfilemp', 'PerfilEmpController');
  // PERFIS
  Route::get('/perfil_emp', 'HomeController@perfil_emp')->name('perfil_emp');
  Route::get('/perfil_usu', 'HomeController@perfil_usu')->name('perfil_usu');
  // USUARIOS
  Route::resource('usuario', 'UserController');
  Route::get('usuario/apaga/{id}','UserController@apaga')->name('apaga_usuario');
  Route::get('usuario/trocaSenha/{id}','UserController@trocaSenha')->name('trocaSenha_usuario');
  // GRUPOS
  Route::resource('grupo', 'GrupoController');
  Route::get('grupo/apaga/{id}','GrupoController@apaga')->name('apaga_grupo');
  // EMPRESAS
  Route::resource('empresa', 'EmpresaController');
  Route::get('empresa/apaga/{id}','EmpresaController@apaga')->name('apaga_empresa');
  // CLIENTES
  Route::resource('cliente', 'ClienteController');
  Route::get('cliente/apaga/{id}','ClienteController@apaga')->name('apaga_cliente');
  // ARQUIVOS
  Route::resource('arquivo', 'ArquivoController');
  Route::post('arquivo/SalvarArqS3/', 'ArquivoController@SalvarArqS3')->name('arquivos3');
  Route::post('arquivo/SalvarArquivos/', 'ArquivoController@SalvarArquivos')->name('arquivos');
  Route::get('arquivo/apaga/{id}','ArquivoController@apaga')->name('apaga_arquivo');
  Route::get('arquivo/baixar/{id}','ArquivoController@baixar')->name('baixar');
  Route::get('arquivo/salvaPdf/{id}/{end}','ArquivoController@salvaPdf')->name('salvaPdf');
  // PASTAS
  Route::resource('pasta', 'PastaController');
  Route::get('pasta/apaga/{id}','PastaController@apaga')->name('apaga_pasta');
  Route::get('pasta/abrir/{tipo}','PastaController@abrir')->name('abrir');
  // PERMISSAO
  Route::resource('permissao', 'PermissaoController');
  Route::post('permissao/mostrar','PermissaoController@mostrar')->name('mostrar_permissao');
  Route::get('permissao/compartilhar/{id}','PermissaoController@compartilhar')->name('compartilhar_permissao');
  Route::post('permissao/compStore/','PermissaoController@compStore')->name('compStore_permissao');
  Route::get('permissao/apagaPermissao/{id}','PermissaoController@apagaPermissao')->name('apagaPermissao');
  Route::put('permissao/moverpasta','PermissaoController@update');
  // SENDMAIL
  Route::get('mailsend/','MailController@SendEmail')->name('mailsend');
  Route::get('mailsend/cadastrado/{email}/{senha}/{empresa}','MailController@SendEmailCad')->name('user_cadastrado');
  Route::get('mailsend/trocaSenha/{email}/{senha}/{nome}','MailController@trocaSenha')->name('mailTrocaSenha');
  Route::get('mailsend/fluxo/{id}/{email}','MailController@fluxo')->name('mailFluxo');
  // TEMPLATE
  Route::resource('template', 'TemplateController');
  Route::get('template/apaga/{id}','TemplateController@apaga')->name('apaga_template');
  // DOCUMENTO fluxoAcao
  Route::resource('documento', 'DocumentoController');
  Route::get('documento/apaga/{id}','DocumentoController@apaga')->name('apaga_documento');
  Route::put('documento/rename/{id}','DocumentoController@rename')->name('renomear_documento');
  Route::get('documento/createDoc/{pasta}','DocumentoController@createDoc')->name('createDoc');
  Route::post('documento/createDocs','DocumentoController@createDocs')->name('createDocs');
  Route::get('documento/createTem/{pasta}','DocumentoController@createTem')->name('createTem');
  Route::post('documento/createDocTem/','DocumentoController@createDocTem')->name('createDocTem');
  Route::get('documento/pdf/{id}','DocumentoController@pdf')->name('pdf');
  Route::get('documento/enviaPdf/{id}/{emal}','DocumentoController@enviaPdf');
  Route::get('documento/reabreDoc/{id}','DocumentoController@reabreDoc')->name('reabreDoc');
  Route::post('documento/busca/','DocumentoController@busca')->name('buscar');
  Route::get('documento/show2/{id}/{end?}','DocumentoController@show2')->name('show2');
  Route::get('documento/fluxoAcao/{id}','DocumentoController@fluxoAcao')->name('fluxoAcao');
  Route::get('documento/download/{id}','DocumentoController@download');
  // FLUXO
  Route::resource('fluxo', 'FluxoController');
  Route::get('fluxo/apagaFluxo/{id}','FluxoController@apaga')->name('apagaFluxo');
  // CEP
  Route::post('consultaCEP','CepController@consultaCEP')->name('consultaCEP');
  // MOLDURA
  Route::resource('moldura', 'MolduraC');
  Route::get('moldura/apaga/{id}','MolduraC@apaga')->name('apaga_moldura');

  Route::get('session/get/{id}','SessionController@getSession');
  //Route::get('session/put/{id}/{id}','SessionController@putSession');
  Route::get('session/forget','SessionController@forgetSession');

  Route::get('/imprimir-documento/{id}', 'DocumentoController@Imprimir');
  Route::post('imprimir-moldura/', 'DocumentoController@ImprimirMoldura')->name('ImprimirMoldura');

  Route::get('/cabecalho', function() {
    return view('doc.cabecalho');
  })->name('cabecalho');

  Route::get('permissao_binario', function() {
    $binarios = DB::table('sog_permissoes_binario')->get();
    return $binarios;
  });

  Route::get('retorna_emails_cadastrados', 'UserController@RetornaEmails');
});

app/User.php
<?php

namespace Soged;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
  use Notifiable;

  protected $fillable = [
    'empresa_id','name', 'email', 'password','foto'
    ,'telefone', 'endereco_id', 'celular','grupo_id'
  ];

  protected $hidden = [
    'password', 'remember_token',
  ];

  public function grupo(){
    return $this->belongsTo('Soged\Grupo', 'grupo_id');
  }
}

app/Http/Controllers/UserController.php
<?php
namespace Soged\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Soged\Http\Requests\StoreUsuario;
use Illuminate\Support\Facades\Hash;
use Soged\User;
use Soged\Usuario;
use Soged\Grupo;
use Soged\Empresa;
use Soged\Pasta;
use Storage;

class UserController extends Controller
{
  public function __construct(){
    $this->middleware('auth');
  }

  public static function TratarImagem($imagem){
    $imagem_explode = explode(",", $imagem);
    $imagem_decode  = base64_decode($imagem_explode[1]);

    return $imagem_decode;
  }

  public function index(){

    $usu      = Usuario::EmpAct()->get();
    if(\Auth::user()->empresa_id == 1){
      $usu      = Usuario::Active()->get();
    }

    return view('user.listUsers')->with('usuarios', $usu,['success' => 'Compartilhado com sucesso.']);
  }

  public function create(){
    $grupos     = Grupo::Active()
    ->where('empresa_id', \Auth::user()->empresa_id)
    ->get();
    $empresas   = Empresa::Active()->get();
    return view('user.usuario', compact('grupos','empresas'));
  }

  protected function validator(array $data){
    return Validator::make($data, [
      'name'        => 'required|string|max:255',
      'email'       => 'required|string|email|max:255|unique:users',
      'password'    => 'required|string|min:6|confirmed',
    ]);
  }

  protected function store(Request $request){

    $hrp            = str_random(8);
    $data           = $request->all();
    $filename = '';

    if($data['foto'] != null) {
      $img          = $this->TratarImagem($data['foto']);
      $pasta        = 'empresas/'.$data['empresa_id'].'/foto_perfil/';
      $filename     = str_random(8).date('ymdhis').'.png';

      Storage::disk('s3')->delete($filename);
      $s3           = Storage::disk('s3')->put($filename,$img, 'public');
    }

    $usu            = Usuario::create([
      'name'        => $data['name'],
      'email'       => $data['email'],
      'password'    => bcrypt($data['password']),
      'grupo_id'    => $data['grupo_id'],
      'empresa_id'  => $data['empresa_id'],
      'foto'        => $filename
    ]);

    Pasta::create(['pasta' => $usu->empresa_id.'p'.$usu->id,'user_id' => $usu->id]);
    Pasta::create(['pasta' => $usu->empresa_id.'a'.$usu->id,'user_id' => $usu->id]);
    Pasta::create(['pasta' => $usu->empresa_id.'c'.$usu->id,'user_id' => $usu->id]);
    Pasta::create(['pasta' => $usu->empresa_id.'t'.$usu->id,'user_id' => $usu->id]);

    return redirect()->action('UserController@index');

  }

  public function show($id){

    $grupos         = Grupo::Active()->EmpId()->get();
    $empresa        = Empresa::Active()->get();

    return view('user.usuario')->with('grupos', $grupos)->with('empresas',$empresa)->with('empresa',$id);
  }

  public function edit($id){
    $grupos     = Grupo::Active()
    ->where('empresa_id', \Auth::user()->empresa_id)
    ->get();
    $empresa        = Empresa::Active()->get();
    return view('user.usuario')->with('usuario', User::find($id))->with('grupos', $grupos)->with('empresas',$empresa);
  }

  public function update(Request $request, $id){

    $id = User::findOrFail($id);
    $id->name = $request['name'];
    $id->email = $request['email'];
    $id->password = bcrypt($request['password']);
    $id->grupo_id = $request['grupo_id'];
    $id->empresa_id = $request['empresa_id'];

    $id->save();

    return redirect()->route('usuario.index');
  }

  public function apaga($id){
    User::where('id',$id)->update(['status' => 0]);

    return redirect()->route('usuario.index');
  }

  public function trocaSenha(User $id){
    $hrp            = str_random(8);
    $id->password   = bcrypt($hrp);
    $id->save();
    $ee = 'desenvolvimento06soitic@gmail.com';

    return redirect('mailsend/trocaSenha/'.$ee.'/'.$hrp.'/'.$id->name);
  }

  public function RetornarUsuarios(){

    $id_empresa = \Auth::user()->empresa_id;
    $usuarios = User::where('empresa_id',$id_empresa)->get();

    return response()->json($usuarios);
  }

  public function RetornaEmails(){
    $usuarios = User::all();

    return response()->json($usuarios);
  }
}

resources/views/user/grupo.blade.php
@extends('layouts.soged')

@section('content')

@php
$c = $r = $u = $d = $up = $dn = $p = '';
if(isset($permissao)) {
  $updn = $permissao->updown;
  $crud = $permissao->crud;
  if($crud > 7) $d        = 'checked';
  if($crud % 2 != 0) $r   = 'checked';
  if($crud==2 or $crud==3 or $crud==6 or $crud==7 or $crud==10 or $crud==11 or $crud==14 or $crud==15) $c='checked';
  if($crud==4 or $crud==5 or $crud==6 or $crud==7 or $crud==12 or $crud==13 or $crud==14 or $crud==15) $u='checked';
  if($updn > 3) $p        = 'checked';
  if($updn % 2 != 0) $dn  = 'checked';
  if($updn==2 or $updn==3 or $updn==6 or $updn==7 or $updn==10 or $updn==11 or $updn==14 or $updn==15) $up='checked';
}
@endphp

<div class="container-fluid">

  <div class="card">

    <div class="mb-2 card-header">

      <div class="p-1">
        <i class="fa fa-key"></i>
        <strong>{{ isset($grupo)?"Alterando Usuário":"Cadastrar Grupo"}}</strong>
      </div>
      
    </div>

    <div class="container">

      <div class="col-12 col-lg-6">

        @if (isset($grupo))
        <form class="pb-5 form" action="{{route('grupo.update',$grupo->id_grupo)}}" method="post">
          {{ method_field('PUT') }}
          @else
          <form class="pb-5 form" method="POST" action="{{ route('grupo.store') }}">
            @endif
            {{ csrf_field() }}
            <input type="hidden" name="empresa_id" value="{{ Auth::user()->empresa_id }}">

            <div class="row">

              <div class="form-group col-12">
                <label for="grupo">Nome do Grupo </label>
                <input id="grupo" type="text" class="form-control form-control-sm required" name="grupo" value="{{ $grupo->grupo or old('grupo') }}" required autofocus>
                @if ($errors->has('grupo'))
                <span class="help-block">
                  <strong>{{ $errors->first('grupo') }}</strong>
                </span>
                @endif
              </div>

            </div>

            @if (!isset($grupo))
            <button type="submit" class="btn btn-primary salvar-cadastro">
              Cadastrar
            </button>
            @else
            <button type="submit" class="btn btn-primary salvar-cadastro">
              Alterar
            </button>
            @endif 

          </div> 

        </form>
      </div>
    </div>

    @endsection

resources/views/user/listGrupos.blade.php
@extends('layouts.soged')

@section('content')
<div class="container-fluid">
  <div class="card mb-3">

    <div class="card-header">

      <div>
        <i class="fa fa-users"></i>
        <strong>Lista de Grupos</strong>
      </div>
      
      <div>
        <div class="text-right">
          <a class="btn btn-primary" href="{{route('grupo.create')}}" title="Cadastrar Grupo">
            <i class="text-white fa fa-plus" aria-hidden="true"></i>
          </a>
        </div>
      </div>

    </div>

    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Nome</th>
              <th>Criação</th>
              <th class="text-center">Ações</th>
            </tr>
          </thead>
          <tbody>
            @foreach ($grupos as $key)
            <tr>
              <td>{{ $key->grupo }}</td>
              <td>{{ date( 'd/m/Y h:m' , strtotime($key->created_at)) }}</td>
              <td class="actions">
                <a href="{{route('grupo.edit',$key->id_grupo)}}" title="Alterar Usuário"><i class="fa fa-edit" aria-hidden="true"></i>
                </a>
                <a href="{{route('apaga_grupo',$key->id_grupo)}}" title="Excluir Usuário" class="excluir-registro">
                  <i class="text-danger fa fa-trash-alt" aria-hidden="true"></i>
                </a>
              </td>
            </tr>
            @endforeach

          </tbody>
        </table>
      </div>
    </div>
    <div class="card-footer small text-muted">Consultado por {{\Auth::user()->name}} em {{date('d/m/Y H:i')}}</div>
  </div>
</div>
@endsection

resources/views/user/listUsers.blade.php
@extends('layouts.soged')

@section('content')
<div class="container-fluid">
	<div class="card mb-3">

		<div class="card-header">

			<div>
				<i class="fa fa-key"></i>
				<strong>Usuários</strong>
			</div>
			
			<div>
				<div class="text-right">
					<a class="btn btn-primary" href="{{route('usuario.create')}}" title="Cadastrar Usuário">
						<i class="text-white fa fa-plus" aria-hidden="true"></i>
					</a>
				</div>
			</div>

		</div>

		<div class="card-body">
			<div class="table-responsive">
				<table class="table table-hover" id="dataTable" width="100%" cellspacing="0">
					<thead>
						<tr>
							<th>Nome</th>
							<th>Email</th>
							<th>Grupo</th>
							<th>Criação</th>
							<th class="text-center">Ações</th>
						</tr>
					</thead>
					<tbody>
						@foreach ($usuarios as $key)
						<tr>
							<td>{{ $key->name }}</td>
							<td>{{ $key->email }}</td>
							<td>{{ $key->grupo['grupo'] }}</td>
							<td>{{ date( 'd/m/Y h:m' , strtotime($key->created_at)) }}</td>
							<td class="actions">
								{{-- <a href="{{route('trocaSenha_usuario',$key->id)}}" title="Gera nova senha" onclick="return confirm('Confirma a alteração de senha?')">
									<i class="fa fa-key text-success" aria-hidden="true"></i>
								</a> --}}
								<a href="{{route('usuario.edit',$key->id)}}" title="Alterar Usuário">
									<i class="fa fa-edit" aria-hidden="true"></i>
								</a>
								<a href="{{route('apaga_usuario',$key->id)}}" title="Excluir Usuário" class="excluir-registro">
									<i class="text-danger fa fa-trash-alt" aria-hidden="true"></i>
								</a>
							</td>
						</tr>
						@endforeach

					</tbody>
				</table>
			</div>
		</div>
		<div class="card-footer small text-muted">Consultado por {{\Auth::user()->name}} em {{date('d/m/Y H:i')}}</div>
	</div>
</div>

@if (session('success'))
<script type="text/javascript">
	window.swal({
		type: 'success',
		title: 'Sucesso',
		text: '{{ session("success") }}',
	});
</script>
@endif
@endsection

resources/views/user/usuario.blade.php
@extends('layouts.soged')

@section('content')
@php
$idG = 0;
$idE = 0;
if(isset($usuario)) $idG = $usuario->grupo_id;
if(isset($usuario)) $idE = $usuario->empresa_id;
if(isset($empresa)) $idE = $empresa;
@endphp

<div class="container-fluid">

	<div class="card">
		<div class="mb-2 card-header">

			<div class="p-1">
				<strong>{{ isset($usuario)?"Alterando Usuário":"Cadastrar Usuário"}}</strong>
			</div>

		</div>

		<div class="container">

			<div class="col-12 col-lg-6">

				@if (isset($usuario))
				<form class="pb-5 form" id="usuario_form" action="{{route('usuario.update',$usuario->id)}}" method="post">
					{{ method_field('PUT') }}
					@else
					<form class="pb-5 form" id="form_store" method="POST" action="{{ route('usuario.store') }}">
						@endif
						{{ csrf_field() }}

						<div class="row">

							<div class="form-group col-12">
								<label for="cliente">Nome</label>
								<input id="name" type="text" class="form-control form-control-sm required" name="name" value="{{ $usuario->name or old('name') }}" required autofocus>
							</div>

						</div>

						<div class="row">

							<div class="form-group col-12">
								<label for="email">E-Mail</label>

								<input id="email" type="email" class="form-control form-control-sm required" name="email" value="{{ $usuario->email or old('email') }}" required {{isset($usuario->email) ? 'disabled' : '' }}>
								<small style="display: none" id="email_erro">O email digitado já existe.</small>
							</div>

						</div>

						<div class="row">
							<div class="form-group col-12 col-lg-6">
								<label for="password">Senha</label>
								<input id="password" type="password" class="form-control form-control-sm required" name="password" required>
							</div>

							<div class="form-group col-12 col-lg-6">
								<label for="password-confirm">Confirma Senha</label>
								<input id="password-confirm" type="password" class="form-control form-control-sm required" name="password_confirmation" required>
							</div>
						</div>

						<div class="row">
							<div class="form-group col-12">
								<label for="grupo">Grupo</label>
								<select name="grupo_id" class="form-control required" id="grupo">
									@foreach ($grupos as $key)
									@if ($key->status != 0)											
									<option value="{{$key->id_grupo}}" {{ $idG == $key->id_grupo ? "selected" : ""}}>{{$key->grupo}}</option>
									@endif
									@endforeach
								</select>
							</div>
						</div>

						<div class="row">
							@if (Auth::user()->empresa_id == 1)
							<div class="form-group col-12">
								<label for="empresa">Empresa</label>
								<select name="empresa_id" class="form-control required" id="empresa">
									@foreach ($empresas as $key)
									<option value="{{$key->id_empresa}}" {{ $idE == $key->id_empresa?"selected":""}}>{{$key->empresa}}</option>
									@endforeach
								</select>
							</div>
							@else
							<input type="hidden" name="empresa_id" value="{{Auth::user()->empresa_id}}">
							@endif
						</div>

						<div class="row">

							@isset($usuario)
							<div class="m-3">
								<img src="{{ env('APP_S3').$usuario->foto }}" alt="" width="200">
							</div>
							@endisset

							<div class="">
								<div class="demo-wrap upload-demo form-group">

									<label>{{ isset($usuario)?"Trocar foto":" Foto" }}</label>
									<div>
										<a class="btn file-btn btn-primary">
											<span>Enviar</span>
											<input type="file" id="upload" value="Choose a file" accept="image/*" />
										</a>

										<button type="button" class="upload-result btn btn-secondary">Cortar</button>
										<button type="button" id="remover_marcadagua" class="btn btn-danger"><i class="fa fa-trash"></i></button>
									</div>

									<div class="upload-msg my-3">
										<i class="fa fa-image fa-2x"></i>
									</div>

									<div class="my-3">
										<img src="" width="150" height="150" class="uploaded-img">
									</div>

									<div class="upload-demo-wrap my-3">
										<div id="upload-demo"></div>
									</div>

								</div>
							</div>
						</div>

						<input type="hidden" name="foto" value="" id="foto-cortada">

						@if (!isset($usuario))
						<button type="submit" id="submit_button" class="btn btn-primary loader-button">
							Salvar
						</button>
						@else
						<button type="submit" id="submit_button" class="btn btn-primary loader-button">
							Salvar
						</button>
						@endif

					</div>

				</form>
			</div>
		</div>

		<script>

			var verificar_corte = 0;
			var counter_email = 0;

			$(document).ready(function(){
				var $uploadCrop;

				function readFile(input) {
					if (input.files && input.files[0]) {
						var reader = new FileReader();

						reader.onload = function (e) {
							$('.upload-demo').addClass('ready');
							$uploadCrop.croppie('bind', {
								url: e.target.result
							}).then(function(){
							});

						}

						reader.readAsDataURL(input.files[0]);
					}
					else {
						swal("Desculpe, seu navegador não suporta esse recurso");
					}
				}

				$uploadCrop = $('#upload-demo').croppie({
					viewport: {
						width: 150,
						height: 150,
						type: 'square'
					},
					enableExif: true,
					boundary: {
						width: 200,
						height: 200
					}
				});

				$('#upload').on('change', function () {
					readFile(this);
				});

				$('.upload-result').on('click', function (ev) {

					var size = { width: 150, height: 150 };

					$uploadCrop.croppie('result', {
						type: 'canvas',
						size: size
					}).then(function (resp) {

						$('#foto-cortada').val(resp);
						$('.uploaded-img').attr('src', resp);
						$('.uploaded-img').show();
						$('.upload-msg').hide();
						$('.upload-demo').removeClass('ready');
						verificar_corte++;
					});
				});

			});

			$('#submit_button').click(function(e){

				e.preventDefault();

				var counter = 0;

				$('.required').each(function() {

					if($(this).val() == '' && $(this).parent().css('display') == 'block'){
						$(this).css('box-shadow','0 0 8px 0 red');
						counter++;
					}
					else{
						$(this).css('box-shadow','none');
					}

				});

				if(counter_email == 0){
					if(counter !=0){
						window.swal({
							type: 'error',
							title: 'Ops...',
							text: 'Preencha os campos em destaque!',
						});
					}
					else{
						if($('#password').val() === $('#password-confirm').val()){
							if($('#upload').val() == "" || verificar_corte > 0){

								$('.form').submit();
							}
							else{
								swal("Corte a imagem antes de salvar.");
							}
						}
						else{
							swal("As senhas não conferem!");
						}
					}
				}
				else{
					window.swal({
						type: 'error',
						title: 'Ops...',
						text: 'O email já está sendo utilizado!',
					});
				}

				


			});

			$('#remover_marcadagua').click(function(){

				$('.upload-demo').removeClass('ready');
				$('.uploaded-img').hide();
				$('.upload-msg').show();
				$('#foto-cortada').val('');
				$('#upload').val('');
				verificar_corte = 0;

			});

			$('#email').blur(function(){
				$('#email').css('box-shadow','none');
				$('#email_erro').hide();
				$.ajax({
					url:'/retorna_emails_cadastrados',
					type:'GET',
					success: function(result){
						var email = $('#email').val();
						counter_email = 0;

						for (var i = result.length - 1; i >= 0; i--) {
							console.log(result[i].email);
							if(email == result[i].email){
								counter_email++;
							}
						}
						if(counter_email > 0){
							$('#email').css('box-shadow','0 0 8px 0 red');
							$('#email_erro').show();
							counter_email++;
						}

					}
				});
			});


		</script>

		@endsection