routes/web.php
<?php

Route::get('/info', function () { phpinfo(); });

Route::get('/', function () { return view('auth.login'); });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/teste', 'HomeController@teste2')->name('teste');
// ------------------------------------------------------------------------
Route::group(['middleware' => ['auth']], function(){
  Route::get('inicial', function () {
    if(Auth::user()->empresa_id == 1) return redirect()->route('empresa.index');
      if(Auth::user()->empresa_id > 1) return redirect()->route('pasta.index');
      });
  // ALERTAS
  Route::resource('alerta', 'AlertaController');
  // PERFIL
  Route::post('/perfil/SalvarImgS3/', 'PerfilController@SalvarImgS3')->name('fotoperfil');
  Route::resource('perfil', 'PerfilController');
  Route::post('/perfilemp/SalvarImgS3/', 'PerfilEmpController@SalvarImgS3')->name('fotoemp');
  Route::resource('perfilemp', 'PerfilEmpController');
  // PERFIS
  Route::get('/perfil_emp', 'HomeController@perfil_emp')->name('perfil_emp');
  Route::get('/perfil_usu', 'HomeController@perfil_usu')->name('perfil_usu');
  // USUARIOS
  Route::resource('usuario', 'UserController');
  Route::get('usuario/apaga/{id}','UserController@apaga')->name('apaga_usuario');
  Route::get('usuario/trocaSenha/{id}','UserController@trocaSenha')->name('trocaSenha_usuario');
  // GRUPOS
  Route::resource('grupo', 'GrupoController');
  Route::get('grupo/apaga/{id}','GrupoController@apaga')->name('apaga_grupo');
  // EMPRESAS
  Route::resource('empresa', 'EmpresaController');
  Route::get('empresa/apaga/{id}','EmpresaController@apaga')->name('apaga_empresa');
  // CLIENTES
  Route::resource('cliente', 'ClienteController');
  Route::get('cliente/apaga/{id}','ClienteController@apaga')->name('apaga_cliente');
  // ARQUIVOS
  Route::resource('arquivo', 'ArquivoController');
  Route::post('arquivo/SalvarArqS3/', 'ArquivoController@SalvarArqS3')->name('arquivos3');
  Route::post('arquivo/SalvarArquivos/', 'ArquivoController@SalvarArquivos')->name('arquivos');
  Route::get('arquivo/apaga/{id}','ArquivoController@apaga')->name('apaga_arquivo');
  Route::get('arquivo/baixar/{id}','ArquivoController@baixar')->name('baixar');
  Route::get('arquivo/salvaPdf/{id}/{end}','ArquivoController@salvaPdf')->name('salvaPdf');
  // PASTAS
  Route::resource('pasta', 'PastaController');
  Route::get('pasta/apaga/{id}','PastaController@apaga')->name('apaga_pasta');
  Route::get('pasta/abrir/{tipo}','PastaController@abrir')->name('abrir');
  // PERMISSAO
  Route::resource('permissao', 'PermissaoController');
  Route::post('permissao/mostrar','PermissaoController@mostrar')->name('mostrar_permissao');
  Route::get('permissao/compartilhar/{id}','PermissaoController@compartilhar')->name('compartilhar_permissao');
  Route::post('permissao/compStore/','PermissaoController@compStore')->name('compStore_permissao');
  Route::get('permissao/apagaPermissao/{id}','PermissaoController@apagaPermissao')->name('apagaPermissao');
  Route::put('permissao/moverpasta','PermissaoController@update');
  // SENDMAIL
  Route::get('mailsend/','MailController@SendEmail')->name('mailsend');
  Route::get('mailsend/cadastrado/{email}/{senha}/{empresa}','MailController@SendEmailCad')->name('user_cadastrado');
  Route::get('mailsend/trocaSenha/{email}/{senha}/{nome}','MailController@trocaSenha')->name('mailTrocaSenha');
  Route::get('mailsend/fluxo/{id}/{email}','MailController@fluxo')->name('mailFluxo');
  // TEMPLATE
  Route::resource('template', 'TemplateController');
  Route::get('template/apaga/{id}','TemplateController@apaga')->name('apaga_template');
  // DOCUMENTO fluxoAcao
  Route::resource('documento', 'DocumentoController');
  Route::get('documento/apaga/{id}','DocumentoController@apaga')->name('apaga_documento');
  Route::put('documento/rename/{id}','DocumentoController@rename')->name('renomear_documento');
  Route::get('documento/createDoc/{pasta}','DocumentoController@createDoc')->name('createDoc');
  Route::post('documento/createDocs','DocumentoController@createDocs')->name('createDocs');
  Route::get('documento/createTem/{pasta}','DocumentoController@createTem')->name('createTem');
  Route::post('documento/createDocTem/','DocumentoController@createDocTem')->name('createDocTem');
  Route::get('documento/pdf/{id}','DocumentoController@pdf')->name('pdf');
  Route::get('documento/enviaPdf/{id}/{emal}','DocumentoController@enviaPdf');
  Route::get('documento/reabreDoc/{id}','DocumentoController@reabreDoc')->name('reabreDoc');
  Route::post('documento/busca/','DocumentoController@busca')->name('buscar');
  Route::get('documento/show2/{id}/{end?}','DocumentoController@show2')->name('show2');
  Route::get('documento/fluxoAcao/{id}','DocumentoController@fluxoAcao')->name('fluxoAcao');
  Route::get('documento/download/{id}','DocumentoController@download');
  // FLUXO
  Route::resource('fluxo', 'FluxoController');
  Route::get('fluxo/apagaFluxo/{id}','FluxoController@apaga')->name('apagaFluxo');
  // CEP
  Route::post('consultaCEP','CepController@consultaCEP')->name('consultaCEP');
  // MOLDURA
  Route::resource('moldura', 'MolduraC');
  Route::get('moldura/apaga/{id}','MolduraC@apaga')->name('apaga_moldura');

  Route::get('session/get/{id}','SessionController@getSession');
  //Route::get('session/put/{id}/{id}','SessionController@putSession');
  Route::get('session/forget','SessionController@forgetSession');

  Route::get('/imprimir-documento/{id}', 'DocumentoController@Imprimir');
  Route::post('imprimir-moldura/', 'DocumentoController@ImprimirMoldura')->name('ImprimirMoldura');

  Route::get('/cabecalho', function() {
    return view('doc.cabecalho');
  })->name('cabecalho');

  Route::get('permissao_binario', function() {
    $binarios = DB::table('sog_permissoes_binario')->get();
    return $binarios;
  });

  Route::get('retorna_emails_cadastrados', 'UserController@RetornaEmails');
});

resources/views/includes/alert.blade.php
<!-- MESSAGE ALERT -->
<div>
{{--   @if (session('success'))
    <script>setTimeout("document.getElementById('alerta-1').style.display = 'none'", 5000);</script>
    <p id="alerta-1" class="alert alert-success">{{ session('success') }}</p>
  @endif
  @if (session('danger'))
    <script>setTimeout("document.getElementById('alerta-1').style.display = 'none'", 5000);</script>
    <p id="alerta-1" class="alert alert-danger">{{ session('danger') }}</p>
  @endif


  @if (session('download'))
    @php
      $download = session('download');
      //dd($download);
      header("Location: '.$download.'");

    @endphp
    <img src="{{$download}}" alt="" download>
  @endif --}}
</div>
<!-- MESSAGE ALERT   -->

resources/views/includes/backup_menu.blade.php
@php
$alertas = session()->pull('teste');
$bell = 'fa-bell-slash-o';
@endphp
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
	<!-- Navigation-->
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
		<a class="navbar-brand" href="pasta">{{ config('app.name', 'Laravel') }}</a>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<!-- MENU LATERAL -->
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
					<a class="nav-link" href="{{route("perfil.index")}}">
						<img src="{{env('APP_S3').Auth::user()->foto}}" alt="..." class="img-responsive" width="30" >
						<span class="nav-link-text">{{ Auth::user()->name }} {{ Auth::user()->empresa_id }} {{ Auth::user()->grupo_id }}</span>
					</a>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard" style="display: {{ Auth::user()->empresa_id==1?"":"none" }}">
					<a class="nav-link" href="{{url("empresa")}}">
						<i class="fa fa-fw fa-industry"></i>
						<span class="nav-link-text">Empresas</span>
					</a>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard" style="display: {{ Auth::user()->empresa_id==1?"none":"" }}">
					<a class="nav-link" href="{{url("cliente")}}">
						<i class="fa fa-fw fa-users"></i>
						<span class="nav-link-text">Clientes</span>
					</a>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components" style="display: {{ Auth::user()->grupo_id < 3?"":"none" }}">
					<a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
						<i class="fa fa-fw fa-user"></i>
						<span class="nav-link-text">Usuários</span>
					</a>
					<ul class="sidenav-second-level collapse" id="collapseComponents">
						<li>
							<a href="{{route("grupo.index")}}">Grupos de Usuários</a>
						</li>
						<li>
							<a href="{{route("usuario.index")}}">Usuários</a>
						</li>
					</ul>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables" style="display: {{ Auth::user()->grupo_id==2?"":"none" }}">
					<a class="nav-link" href="{{route("fluxo.index")}}">
						<i class="fa fa-sort-amount-asc"></i>
						<span class="nav-link-text">Fluxos</span>
					</a>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables" style="display: {{ Auth::user()->empresa_id==1?"none":"" }}">
					<a class="nav-link" href="{{route("template.index")}}">
						<i class="fa fa-fw fa-file"></i>
						<span class="nav-link-text">Tipos de Templates</span>
					</a>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Documentos" style="display: {{ Auth::user()->empresa_id==1?"none":"" }}">
					<a class="nav-link" href="{{url("pasta")}}">
						<i class="fa fa-fw fa-folder"></i>
						<span class="nav-link-text">Meus documentos </span>
					</a>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels" style="display:none">
					<a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
						<i class="fa fa-fw fa-sitemap"></i>
						<span class="nav-link-text">Menu Levels</span>
					</a>
					<ul class="sidenav-second-level collapse" id="collapseMulti">
						<li>
							<a href="#">Second Level Item</a>
						</li>
						<li>
							<a href="#">Second Level Item</a>
						</li>
						<li>
							<a href="#">Second Level Item</a>
						</li>
						<li>
							<a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Third Level</a>
							<ul class="sidenav-third-level collapse" id="collapseMulti2">
								<li>
									<a href="#">Third Level Item</a>
								</li>
								<li>
									<a href="#">Third Level Item</a>
								</li>
								<li>
									<a href="#">Third Level Item</a>
								</li>
							</ul>
						</li>
					</ul>
				</li>

				<li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link" style="display:none">
					<a class="nav-link" href="#">
						<i class="fa fa-fw fa-link"></i>
						<span class="nav-link-text">Link</span>
					</a>
				</li>
			</ul>

			<!-- MENU SUPERIOR -->
			<ul class="navbar-nav sidenav-toggler">
				<li class="nav-item">
					<a class="nav-link text-center" id="sidenavToggler">
						<i class="fa fa-fw fa-angle-left"></i>
					</a>
				</li>
			</ul>
			<ul class="navbar-nav ml-auto">
				<!-- Notificação -->
				<li class="nav-item dropdown">

					

					<div class="dropdown-menu" aria-labelledby="alertsDropdown">
						<h6 class="dropdown-header">&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;:&nbsp;:&nbsp; NOTIFICAÇÕES E ALERTAS &nbsp;:&nbsp;:&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp;</h6>
						<div class="dropdown-divider"></div>

						@if ($alertas != NULL)
						@foreach ($alertas as $key)
						@if (Auth::id() == $key->user_id)
						@php
						$text = 'text-success';
						$bell = 'fa-bell';
						if($key->status == 2)   $text = 'text-dark';
						if($key->tipo == 1)     $icone = "fa fa-hand-o-right";
						elseif($key->tipo == 2) $icone = "fa fa-envelope-o";
						elseif($key->tipo == 3) $icone = "fa fa-thumbs-o-up";

						@endphp

						<a class="dropdown-item" href="{{route('alerta.edit',$key->id_alert)}}">
							<span class="{{$text}}">
								<strong>
									<i class="{{$icone}} fa-fw"></i> {{ $key->alerta or 'Sem alertas' }}</strong>
								</span>
								<span class="small float-right text-muted" title="{{ date( 'd/m/Y' , strtotime($key->created_at)) }}">
									{{ date( 'h:m' , strtotime($key->created_at)) }}</span>
									<div class="dropdown-message small">{{ $key->desc or '' }}</div>
								</a>
								<div class="dropdown-divider "></div>

								@endif
								@endforeach
								@endif

								<a class="dropdown-item small d-lg-none" href="#">Abrir todos os alertas</a>
							</div>

							

							<a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-fw {{$bell}} fa-lg"></i>
								<span class="d-lg-none">Alerts
									<span class="badge badge-pill badge-warning">6 New</span>
								</span>
								@if ($bell == 'fa-bell')
								<span class="indicator text-danger d-none d-lg-block" title="Alertas">
									<i class="fa fa-fw fa-circle"></i>
								</span>
								@endif
							</a>
						</li>
						<!-- Fim notificação -->
						<!-- BUSCA ARQUIVOS E PASTAS BUSCA ARQUIVOS E PASTAS BUSCA ARQUIVOS E PASTAS BUSCA ARQUIVOS E PASTAS -->
						<li class="nav-item">
							<form class="form-inline my-2 my-lg-0 mr-lg-2" action="{{route("buscar")}}" method="post">
								{{ csrf_field() }}
								<div class="input-group">
									<input class="busca" name="nome" type="text" placeholder="Buscar Arquivos e Pastas">
								</div>
							</form>
						</li>
						<!-- BUSCA ARQUIVOS E PASTAS BUSCA ARQUIVOS E PASTAS BUSCA ARQUIVOS E PASTAS BUSCA ARQUIVOS E PASTAS -->
						<li class="nav-item">
							<div class="row">
								<div class="col-xs-8 col-md-4">
									<a href="{{route("perfilemp.index")}}">
										<img src="{{env('APP_S3').'empresas/fotos/'.\Auth::user()->empresa_id}}.png" alt="..." class="img-responsive" width="30" >
									</a>
								</div>
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link" data-toggle="modal" data-target="#exampleModal">
								<i class="fa fa-fw fa-sign-out"></i>Sair</a>
							</li>
						</ul>
					</div>
				</nav>

resources/views/includes/footer.blade.php
<!-- /.content-wrapper-->
<footer class="p-3">
  <div class="container">
    <div class="text-center">
      <small>Copyright © SOGED 2017</small>
    </div>
  </div>
</footer>

<!-- Logout -->
<form id="logout-form" action="{{ route('logout') }}" method="POST">
  {{ csrf_field() }}
</form>

resources/views/includes/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Soged') }}</title>

    <!-- Styles -->
    <!--
        <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
        <!-- Bootstrap core CSS-->

        <link rel="stylesheet" href="{{URL::asset('/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

        <!-- Custom styles for this template-->

        <link href="{{URL::asset('css/sb-admin.css')}}" rel="stylesheet">
        <link href="{{URL::asset('css/soged.css')}}" rel="stylesheet">
        <link href="{{URL::asset('css/teste.css')}}" media="print" rel="stylesheet">  
        <link href="{{URL::asset('/vendor/datatables/dataTables.bootstrap4.css') }}" rel="stylesheet">
        <link href="{{URL::asset('css/select2.min.css') }}" rel="stylesheet">
        <link href="{{URL::asset('css/custom.css') }}" rel="stylesheet">
        <link href="{{URL::asset('css/lightbox.min.css') }}" rel="stylesheet">
        <link href="{{URL::asset('css/jquery-ui.theme.min.css') }}" rel="stylesheet">
        <link href="{{URL::asset('css/croppie.css') }}" rel="stylesheet">
        <link href="{{URL::asset('css/demo.css') }}" rel="stylesheet">
        

        <script src="{{URL::asset('/vendor/jquery/jquery.min.js')}}"></script>
        <script src="{{URL::asset('/js/jquery-ui.min.js')}}"></script>
        <script src="{{URL::asset('/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
        <!-- Custom scripts for this page-->
        <!-- Page level plugin JavaScript-->
        <script src="{{URL::asset('/vendor/datatables/jquery.dataTables.js')}}"></script>
        <script src="{{URL::asset('/vendor/datatables/dataTables.bootstrap4.js')}}"></script>
        <!-- Core plugin JavaScript-->
        <script src="{{URL::asset('/vendor/jquery-easing/jquery.easing.min.js')}}"></script>
        <!-- Custom scripts for all pages-->
        <script src="{{URL::asset('/js/sb-admin.min.js')}}"></script>
        <!-- Custom scripts for this page-->
        <!-- Toggle between fixed and static navbar-->
        <script src="{{URL::asset('/js/sb-admin-datatables.min.js')}}"></script>

        <script src="{{URL::asset('/js/sweetalert.min.js')}}"></script>

        <script src="{{URL::asset('/js/jquery.mask.min.js')}}"></script>

        <script src="{{URL::asset('/js/select2.min.js')}}"></script>

        <script src="{{URL::asset('/js/interact.min.js')}}"></script>

        <script src="{{URL::asset('/js/custom.js')}}"></script>

        <script src="{{URL::asset('/js/fontawesome.js')}}"></script>

        <script src="{{URL::asset('/js/lightbox.min.js')}}"></script>

        <script src="{{URL::asset('/js/ckeditor.js')}}"></script>

        <script src="{{URL::asset('/js/croppie.js')}}"></script>

        <script src="{{URL::asset('/js/demo.js')}}"></script>

        


    </head>

    <body>

resources/views/includes/menu.blade.php
@php
$alertas = session()->pull('teste');
@endphp
<!-- Sidebar Holder -->
<nav id="sidebar">
	<div class="sidebar-header">

		<div class="perfil mt-3">
			<img src="{{ env('APP_S3').Auth::user()->foto }}" class="img-fluid">

		</div>

		<small>Olá, {{ Auth::user()->name }}</small>

		<ul class="list-inline justify-content-center mb-0">

			<!-- Notificação -->
			{{-- <li class="list-inline-item">
				<a href="#" id="notificacoes-click" style="position: relative">
					<i class="fa fa-bell"></i>
					@if($alertas != NULL)
					<div class="circle"></div>
					@endif
				</a>
			</li> --}}

			<!-- Perfil -->
			<li class="list-inline-item">
				<a href="{{url('usuario/'.Auth::id().'/edit')}}" id="editar"><i class="fa fa-user"></i></a>
			</li>

			<!-- Sair -->
			<li class="list-inline-item">
				<a href="#" id="sair"><i class="fa fa-sign-out-alt"></i></a>
			</li>

		</ul>
	</div>

	<ul class="list-unstyled components">

		@if(Auth::user()->empresa_id!=1)
		<li>
			<a href="{{url('pasta')}}"><i class="fas fa-folder-open mr-2"></i>Meus Documentos</a>
		</li>
		<li>

			<a href="#pageSubmenuM" data-toggle="collapse" aria-expanded="false" id="documentos"><i class="far fa-folder-open mr-2"></i>Outros Locais</a>

			<ul class="collapse list-unstyled" id="pageSubmenuM">
				{{-- <li><a href="{{route('abrir','a')}}"><i class="far fa-thumbs-up mr-2"></i>Documentos aprovados</a></li> --}}
				<li><a href="{{route('abrir','c')}}"><i class="far fa-share-square mr-2"></i>Compartilhado comigo</a></li>
				<li><a href="{{route('abrir','t')}}"><i class="far fa-file-alt mr-2"></i>Templates</a></li>
				<li><a href="{{route('moldura.index')}}"><i class="far fa-file-alt mr-2"></i>Cabeçalhos e rodapés</a></li>
				@if(Auth::user()->empresa_id!=1)
				<li>
					<a href="{{route('template.index')}}">
						<i class="fa fa-file-alt mr-2"></i>
						Categorias Templates
					</a>
				</li>
				@endif
			</ul>
		</li>

		<li>
			<a href="{{url('cliente')}}">
				<i class="fa fa-users mr-2"></i>
				Clientes
			</a>
		</li>
		@endif
		@if(Auth::user()->empresa_id==1)
		<li>
			<a href="{{url('empresa')}}">
				<i class="fa fa-building mr-2"></i>
				Empresas
			</a>
		</li>
		@endif

		@if(Auth::user()->grupo_id < 3)
		<li>
			<a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false">
				<i class="fa fa-key mr-2"></i>
				Usuários
			</a>
			<ul class="collapse list-unstyled" id="pageSubmenu">
				<li><a href="{{route('usuario.index')}}">Usuários</a></li>
				@if(Auth::user()->empresa_id != 1)
				<li><a href="{{route('grupo.index')}}">Grupos de Usuários</a></li>
				@endif
			</ul>
		</li>
		@endif

		@if(Auth::user()->grupo_id==2)
		{{-- <li>
			<a href="{{route('fluxo.index')}}">
				<i class="fa fa-exchange-alt mr-2"></i>
				Fluxos
			</a>
		</li> --}}
		@endif

		


	</ul>
</nav>

<!-- Notificações Lista -->
<div class="overlay-notificacoes"></div>

<div class="menu-notificacoes" aria-labelledby="alertsDropdown" id="notificacoes">
	<h6 class="dropdown-header">&nbsp;&nbsp;&nbsp;&nbsp;:&nbsp;:&nbsp;:&nbsp; NOTIFICAÇÕES E ALERTAS &nbsp;:&nbsp;:&nbsp;:&nbsp;&nbsp;&nbsp;&nbsp;</h6>
	<div class="dropdown-divider"></div>

	@if ($alertas != NULL)
	@foreach ($alertas as $key)
	@if (Auth::id() == $key->user_id)
	@php
	$text = 'text-success';
	$bell = 'fa-bell';
	if($key->status == 2)   $text = 'text-dark';
	if($key->tipo == 1)     $icone = "fa fa-hand-point-right";
	elseif($key->tipo == 2) $icone = "fa fa-envelope";
	elseif($key->tipo == 3) $icone = "fa fa-thumbs-up";

	@endphp

	<a class="dropdown-item" href="{{route('alerta.edit',$key->id_alert)}}">
		<span class="{{$text}}">
			<strong>
				<i class="{{$icone}} fa-fw"></i> {{ $key->alerta or 'Sem alertas' }}
			</strong>
		</span>
		<span class="small float-right text-muted" title="{{ date( 'd/m/Y' , strtotime($key->created_at)) }}">{{ date( 'h:m' , strtotime($key->created_at)) }}</span>
		<div class="dropdown-message small">{{ $key->desc or '' }}</div>
	</a>

	<div class="dropdown-divider "></div>

	@endif
	@endforeach
	@endif
</div>